name: reus_deportiu
description: "App pels clients del Reus Deportiu"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  google_fonts: ^6.3.2
  cloud_firestore: ^6.0.3
  firebase_app_check: ^0.4.1+1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/reusDeportiu.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/